openapi: 3.0.3
info:
  title: affichage
  version: 1.0.1
servers:
    - url: http://lochalost:8000
paths:
  /users:
    get:
      parameters:
      - name: page
        in: query
        schema:
          type: integer
          example: 1
      - name: size
        in: query
        schema:
          type: integer
          example: 20
      responses:
        "200":
          description: ok
          content:
            application/plain:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: Alice
                    email:
                      type: string
                      example: hei.Alice@gmail.com
        400:
          description: mauvaise type de parametre
          content:
            application/json:
              schema:
                properties:
                  error:
                    type: string
                    example: bad types for provided query parameters