openapi: 3.0.3
info:
  title: affichage
  version: 1.0.1
servers:
    - url: http://lochalost:8000
paths:
  /users:
      get:
      parameters:
      - name: page
        in: query
        schema:
          type: integer
          example: 1
            - name: size
            in: query
            schema:
              type: integer
              example: 20
              responses:
                "200":
                  description: ok
