openapi: 3.0.3
info:
 title: Model task
 version: 1.0.0

servers:
  - url: http://localhost:8080

paths:
 /tasks:
   get:
    responses:
      "200":
        description: ok
        content:
          application/plain:
            schema:
              type: array
              items:
                properties:
                  "id":
                    type: integer
                    example: 1
                  "name":
                    type: string
                    example: menage
                  "completed":
                    type: boolean
                    example: false
   post:
    requestBody:
    required: true
    content:
      application/json:
        schema:
          type: object
          requered:
            - id
            - name
            - completed
        propriety:
          id:
            type: integer
            example: 2
          name:
            type: string
            example: cuisiner
          completed:
            type: boolean
            example: true








