openapi: 3.0.3
info:
 title: Model task
 version: 1.0.0

servers:
  - url: http://localhost:8080

paths:
 /tasks:
   get:
    responses:
      "200":
        description: ok
        content:
          application/json:
            schema:
              type: array
              items:
                properties:
                  "id":
                    type: integer
                    example: 1
                  "name":
                    type: string
                    example: menage
                  "completed":
                    type: boolean
                    example: false
   post:
    requestBody:
     required: true
     content:
       application/json:
        schema:
          type: object
          required:
            - id
            - name
            - completed
          properties:
           id:
            type: integer
            example: 2
           name:
            type: string
            example: cuisiner
           completed:
            type: boolean
            example: true
    responses:
        "201":
          description: votre task a été créé
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 2
                  name:
                    type: string
                    example: menage
                  completed:
                    type: boolean
                    example: false
 /tasks/{id}:
   get:
     description: lister les tasks a partir de son id
     parameters:
       - in: query
         name: id
         required: true
         schema:
           type: integer
           example: 4
     responses:
      200:
        description: la liste des tache par id
        content:
          application/json:
           schema:
            type: object
            properties:
              id:
                type: integer
                example: 4
              name:
                type: string
                example: menage
              completed:
                type: boolean
                example: false
   delete:
     description: suppression d un task
     parameters:
       - in: query
         name: id
         required: true
         schema:
           type: integer
     responses:
       "204":
         description: tache supprimer avec succée

 /tasks/:
   delete:
     description: supprimer une liste de tache
     requestBody:
       required: true
       content:
         applicaion/json:
           schema:
             type: array
             items:
               type: integer
             example: [1,2,3]
     responses:
       "200":
         description: suppression des taches
         content:
           application/json:
             schema:
               type: array
               items:
                 type: object
                 properties:
                   id:
                     type: integer
                     example: 3
                   name:
                     type: string
                     example: acheter une produit
                   completed:
                     type: boolean
                     example: done
       "400":
         description: aucune tache trouver
         content:
           application/json:
             schema:
               type: object
               properties:
                 message:
                   type: string
                   example: acune tache

