openapi: 3.0.3
info:
  title: Product API
  version: 1.0.0

paths: {}

components:
  schemas:
    Product:
      type: object
      properties:
        name:
          type: string
          example: "Lait en poudre"
        expiration_datetime:
          type: string
          format: date-time
          example: "2025-12-31T23:59:59Z"
        price:
          type: number
          format: float
          example: 12.50
      required:
        - name
        - expiration_datetime
        - price
